# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ staging ]
      # Push events on staging branch
      # - staging
    tags:
      # Push events to v1.0, v1.1, and v1.9 tags
      - v1.*
  # pull_request:
  #   branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Extract branch name
        if: startsWith(github.ref, 'refs/heads/')
        shell: bash
        run:
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse HEAD)"
        id: extract_branch

        # https://github.community/t/how-to-get-just-the-tag-name/16241
        # SOURCE_NAME : The heads or the tags
        # SOURCE_BRANCH : The [head] or empty
        # SOURCE_TAG : The [tag] or empty
        # echo "::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}"
        # echo "::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}"
        # echo "::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}"
      - name: Extract tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"
        id: extract_tag


      # Runs a single command using the runners shell
      - name: Install Packages
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Build Packages
        run: npm run build

      - name: Create CDN Folder
        shell: bash
        run: mv ./dist ./cdn
        
      - name: Deploy branch
        if: startsWith(github.ref, 'refs/heads/')
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{secrets.PUBLISH_TOKEN}} # Token 
          branch: publish # The branch the action should deploy to.
          #repository-name: cherrybase/cherrybase.github.io # The repo the action should deploy to.
          commit-message: ${{ steps.extract_branch.outputs.SOURCE_NAME }}.${{ steps.extract_branch.outputs.branch }}.${{ steps.extract_branch.outputs.sha_short }}
          folder: . # The folder the action should deploy.
          #target-folder : /
      
      - name: Deploy tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{secrets.PUBLISH_TOKEN}} # Token 
          branch: publish_tag # The branch the action should deploy to.
          #repository-name: cherrybase/cherrybase.github.io # The repo the action should deploy to.
          commit-message: 'Deployment ${{ steps.extract_tag.outputs.tag_name }}'
          folder: . # The folder the action should deploy.
          #target-folder : /
