# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ staging ]
  create:
    tags:
      branches: [ staging ]
  # pull_request:
  #   branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
             echo "::set-output name=sha_short::$(git rev-parse HEAD)"
        id: extract_branch

      # Runs a single command using the runners shell
      - name: Install Packages
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Build Packages
        run: npm run build

      - name: Create CDN Folder
        shell: bash
        run: mv ./dist ./cdn
        
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{secrets.PUBLISH_TOKEN}} # Token 
          branch: publish # The branch the action should deploy to.
          #repository-name: cherrybase/cherrybase.github.io # The repo the action should deploy to.
          commit-message: ${{ steps.extract_branch.outputs.branch }}.${{ steps.extract_branch.outputs.sha_short }}
          folder: . # The folder the action should deploy.
          #target-folder : /
